import type { RicettaComponibile } from './modello'

/**
 * Il ricettario di casa: ricette scritte per posti, non per ingredienti.
 *
 * Sono poche e sono di base apposta. Non deve essere un archivio: deve essere
 * l'elenco delle cose che si cucinano davvero con una lista di ingredienti in
 * mano, scritte in modo che i grammi li metta il tuo pasto. Il catalogo dei
 * siti serve per la varieta', questo serve per la certezza.
 */
export const LIBRO: RicettaComponibile[] = [
  // ─── Colazione ────────────────────────────────────────────────────────────
  {
    id: 'yogurt-strati',
    titolo: 'Yogurt a strati',
    fasce: ['colazione'],
    minuti: 5,
    posti: [
      { chiave: 'yogurt', ruolo: 'latticino', gruppi: ['latticino'] },
      { chiave: 'cereale', ruolo: 'cereale_colazione', gruppi: ['cereale'] },
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    liberi: ['cannella'],
    passi: [
      'Metti {yogurt} sul fondo della ciotola.',
      'Sopra {cereale}, senza mescolare: deve restare croccante.',
      'Chiudi con {frutta} a pezzi e {semi}.',
      'Una spolverata di cannella e via.',
    ],
  },
  {
    id: 'porridge',
    titolo: 'Porridge',
    fasce: ['colazione'],
    minuti: 10,
    posti: [
      { chiave: 'fiocchi', ruolo: 'cereale_colazione', gruppi: ['cereale'] },
      { chiave: 'latte', ruolo: 'latticino', gruppi: ['latticino', 'bevanda'] },
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    liberi: ['cannella', 'un pizzico di sale'],
    passi: [
      'Scalda {latte} in un pentolino, senza farlo bollire.',
      'Butta dentro {fiocchi} e un pizzico di sale.',
      'Mescola sul fuoco basso finché non si addensa: sette minuti, non di più.',
      'Fuori dal fuoco aggiungi {frutta} a pezzi e {semi}.',
    ],
    nota: 'Se lo vuoi più cremoso, spegni un minuto prima: si rapprende da solo nella ciotola.',
  },
  {
    id: 'pane-spalmabile',
    titolo: 'Pane e spalmabile',
    fasce: ['colazione', 'merenda'],
    minuti: 4,
    posti: [
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'] },
      { chiave: 'sopra', ruolo: 'spalmabile', gruppi: ['dolce', 'grasso', 'frutta_secca'] },
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'], facoltativo: true },
    ],
    passi: [
      'Tosta {pane} finché non suona quando lo batti.',
      'Spalma {sopra} mentre è ancora caldo.',
      'Accanto, {frutta}.',
    ],
  },
  {
    id: 'uova-strapazzate-pane',
    titolo: 'Uova strapazzate sul pane',
    fasce: ['colazione', 'pranzo', 'cena'],
    minuti: 10,
    posti: [
      { chiave: 'uova', ruolo: 'proteina', gruppi: ['uova'] },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane', 'cereale'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'], facoltativo: true },
    ],
    liberi: ['sale', 'pepe', 'erba cipollina'],
    passi: [
      'Sbatti {uova} con sale e pepe, appena appena.',
      'Scalda {grasso} in padella a fuoco basso. Basso davvero.',
      'Versa le uova e muovi piano con una spatola: sono pronte quando sono ancora lucide.',
      'Servile su {pane} tostato, con {verdura} accanto.',
    ],
    nota: 'Il fuoco alto le fa diventare gomma. È l’unico errore possibile in questa ricetta.',
  },
  {
    id: 'ricotta-miele',
    titolo: 'Ricotta e miele',
    fasce: ['colazione', 'merenda'],
    minuti: 3,
    posti: [
      { chiave: 'ricotta', ruolo: 'latticino', gruppi: ['latticino'] },
      { chiave: 'dolce', ruolo: 'spalmabile', gruppi: ['dolce'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'], facoltativo: true },
    ],
    passi: [
      'Metti {ricotta} in una ciotola e sbattila con la forchetta finché non diventa liscia.',
      'Sopra {dolce} e {semi}.',
      'Con {pane} accanto.',
    ],
  },

  // ─── Spuntino e merenda ───────────────────────────────────────────────────
  {
    id: 'frutta-secca',
    titolo: 'Frutta e frutta secca',
    fasce: ['spuntino', 'merenda'],
    minuti: 2,
    posti: [
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'] },
      { chiave: 'secca', ruolo: 'snack', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    passi: ['Taglia {frutta}.', 'Accanto {secca}, contata e non a manciate.'],
  },
  {
    id: 'yogurt-veloce',
    titolo: 'Yogurt e frutta',
    fasce: ['spuntino', 'merenda'],
    minuti: 3,
    posti: [
      { chiave: 'yogurt', ruolo: 'latticino', gruppi: ['latticino'] },
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    passi: ['Versa {yogurt} nella ciotola.', 'Aggiungi {frutta} a pezzi e {semi}.'],
  },
  {
    id: 'pane-pomodoro',
    titolo: 'Pane e pomodoro',
    fasce: ['spuntino', 'merenda'],
    minuti: 5,
    posti: [
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['origano', 'sale'],
    passi: [
      'Tosta {pane}.',
      'Sopra {verdura} a fette, {grasso}, origano e sale.',
    ],
  },
  {
    id: 'ricotta-cucchiaio',
    titolo: 'Latticino al cucchiaio',
    fasce: ['spuntino', 'merenda'],
    minuti: 2,
    posti: [
      { chiave: 'latticino', ruolo: 'latticino', gruppi: ['latticino'] },
      { chiave: 'frutta', ruolo: 'frutta', gruppi: ['frutta'], facoltativo: true },
    ],
    liberi: ['cannella'],
    passi: ['Metti {latticino} in una ciotola.', 'Accanto {frutta} e una spolverata di cannella.'],
  },

  // ─── Primi ────────────────────────────────────────────────────────────────
  {
    id: 'pasta-verdure-saltate',
    titolo: 'Pasta saltata con le verdure',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'pasta', ruolo: 'base', gruppi: ['cereale'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'formaggio', ruolo: 'latticino', gruppi: ['latticino'], facoltativo: true },
    ],
    liberi: ['aglio', 'sale', 'pepe', 'prezzemolo'],
    passi: [
      'Metti su l’acqua e salala quando bolle.',
      'Taglia {verdura} a pezzi piccoli e falla appassire con {grasso} e uno spicchio d’aglio.',
      'Cala {pasta} e scolala due minuti prima di quanto dice la scatola.',
      'Saltala in padella con la verdura e un mestolo d’acqua di cottura, finché non si lega.',
      'Fuori dal fuoco {formaggio} e prezzemolo.',
    ],
    nota: 'L’acqua di cottura è quella che lega il piatto. Tienine sempre un mestolo da parte.',
  },
  {
    id: 'pasta-pomodoro',
    titolo: 'Pasta al pomodoro',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'pasta', ruolo: 'base', gruppi: ['cereale'] },
      { chiave: 'pomodoro', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'formaggio', ruolo: 'latticino', gruppi: ['latticino'], facoltativo: true },
    ],
    liberi: ['aglio', 'basilico', 'sale'],
    passi: [
      'Scalda {grasso} con uno spicchio d’aglio schiacciato.',
      'Butta {pomodoro} e fai andare quindici minuti a fuoco medio, con il coperchio storto.',
      'Cuoci {pasta} e scolala nel sugo.',
      'Basilico a fine cottura e {formaggio} nel piatto.',
    ],
  },
  {
    id: 'pasta-legumi',
    titolo: 'Pasta e legumi',
    fasce: ['pranzo', 'cena'],
    minuti: 30,
    posti: [
      { chiave: 'pasta', ruolo: 'base', gruppi: ['cereale'] },
      { chiave: 'legumi', ruolo: 'proteina', gruppi: ['legume'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['aglio', 'rosmarino', 'sale', 'pepe'],
    passi: [
      'Soffriggi aglio e rosmarino in {grasso}.',
      'Aggiungi {legumi} e {verdura} a pezzetti, copri d’acqua e fai sobbollire dieci minuti.',
      'Frulla un terzo del fondo: è quello che rende il piatto cremoso senza panna.',
      'Cuoci {pasta} dentro la stessa pentola, aggiungendo acqua calda quando serve.',
      'Ferma il fuoco quando è ancora brodosa: si asciuga nel piatto.',
    ],
    nota: 'Piatto unico: proteina e carboidrato stanno già dentro.',
  },
  {
    id: 'riso-verdure',
    titolo: 'Riso con le verdure',
    fasce: ['pranzo', 'cena'],
    minuti: 25,
    posti: [
      { chiave: 'riso', ruolo: 'base', gruppi: ['cereale'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['carne', 'pesce', 'uova', 'legume'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['cipolla', 'sale', 'pepe', 'limone'],
    passi: [
      'Lessa {riso} in acqua salata e scolalo al dente.',
      'Intanto salta {verdura} con {grasso} e un po’ di cipolla.',
      'Se c’è, aggiungi {proteina} alla padella e portala a cottura.',
      'Unisci il riso, mescola due minuti a fuoco vivo, chiudi con il limone.',
    ],
  },
  {
    id: 'minestra-cereale',
    titolo: 'Minestra di verdure e cereale',
    fasce: ['pranzo', 'cena'],
    minuti: 35,
    posti: [
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'cereale', ruolo: 'base', gruppi: ['cereale', 'tubero'] },
      { chiave: 'legumi', ruolo: 'proteina', gruppi: ['legume'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['sedano', 'carota', 'cipolla', 'alloro', 'sale'],
    passi: [
      'Fai il fondo con sedano, carota e cipolla in {grasso}.',
      'Aggiungi {verdura} a tocchetti e copri d’acqua, con una foglia d’alloro.',
      'Dopo venti minuti butta {cereale} e {legumi}.',
      'Cuoci finché il cereale non è pronto. Aggiusta di sale alla fine, mai prima.',
    ],
  },
  {
    id: 'vellutata',
    titolo: 'Vellutata',
    fasce: ['cena'],
    minuti: 30,
    posti: [
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura', 'tubero'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'], facoltativo: true },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['legume', 'latticino'], facoltativo: true },
    ],
    liberi: ['cipolla', 'sale', 'pepe'],
    passi: [
      'Rosola la cipolla in {grasso}, unisci {verdura} a pezzi.',
      'Copri d’acqua a filo e cuoci venti minuti, finché non si schiaccia con la forchetta.',
      'Frulla. Se è troppo densa, allunga con l’acqua di cottura.',
      'Aggiungi {proteina} e servi con {pane} tostato a dadini.',
    ],
    nota: 'Acqua a filo, non di più: si allunga sempre, non si restringe mai.',
  },

  // ─── Secondi di carne ─────────────────────────────────────────────────────
  {
    id: 'carne-griglia',
    titolo: 'Carne alla griglia con contorno',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'carne', ruolo: 'proteina', gruppi: ['carne'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'base', ruolo: 'base', gruppi: ['pane', 'cereale', 'tubero'], facoltativo: true },
    ],
    liberi: ['sale', 'pepe', 'rosmarino', 'limone'],
    passi: [
      'Tira fuori {carne} dal frigo venti minuti prima: fredda si stringe e resta dura.',
      'Scalda la griglia finché non fuma appena.',
      'Cuoci senza toccarla, girala una volta sola. Sala dopo.',
      'Fai riposare cinque minuti mentre condisci {verdura} con {grasso} e limone.',
      'Accanto {base}.',
    ],
    nota: 'Il riposo non è facoltativo: senza, il sugo resta sul tagliere invece che nella carne.',
  },
  {
    id: 'pollo-padella-limone',
    titolo: 'Pollo in padella al limone',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'pollo', ruolo: 'proteina', gruppi: ['carne'], escludi: ['carne_rossa'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'base', ruolo: 'base', gruppi: ['cereale', 'pane', 'tubero'], facoltativo: true },
    ],
    liberi: ['limone', 'sale', 'pepe', 'prezzemolo', 'un dito d’acqua'],
    passi: [
      'Taglia {pollo} a fettine sottili e battile un po’.',
      'Scalda {grasso} in padella, rosola il pollo due minuti per lato.',
      'Sfuma con il succo di mezzo limone e un dito d’acqua, copri e lascia due minuti.',
      'Servi con {verdura} e {base}, e il fondo di cottura sopra.',
    ],
  },
  {
    id: 'polpette-forno',
    titolo: 'Polpette al forno',
    fasce: ['pranzo', 'cena'],
    minuti: 40,
    posti: [
      { chiave: 'carne', ruolo: 'proteina', gruppi: ['carne'] },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'], facoltativo: true },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'], facoltativo: true },
      { chiave: 'formaggio', ruolo: 'latticino', gruppi: ['latticino'], facoltativo: true },
    ],
    liberi: ['un uovo', 'prezzemolo', 'sale', 'pepe', 'aglio'],
    passi: [
      'Ammolla {pane} in poca acqua e strizzalo.',
      'Impasta {carne} con il pane, {formaggio}, un uovo, prezzemolo e aglio tritato.',
      'Forma le polpette e mettile su carta forno.',
      'Venticinque minuti a 190°, girandole a metà.',
      'Contorno: {verdura}, che può cuocere nella stessa teglia.',
    ],
  },

  // ─── Secondi di pesce ─────────────────────────────────────────────────────
  {
    id: 'pesce-forno',
    titolo: 'Pesce al forno',
    fasce: ['pranzo', 'cena'],
    minuti: 30,
    posti: [
      { chiave: 'pesce', ruolo: 'proteina', gruppi: ['pesce'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura', 'tubero'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['limone', 'aglio', 'prezzemolo', 'sale', 'olive'],
    passi: [
      'Taglia {verdura} a fette sottili e stendila sul fondo della teglia con {grasso} e sale.',
      'Appoggia sopra {pesce}, con limone e aglio.',
      'Venti minuti a 180°. È pronto quando la carne si stacca dalla lisca senza forzare.',
      'Prezzemolo alla fine, a crudo.',
    ],
  },
  {
    id: 'pesce-padella-pomodorini',
    titolo: 'Pesce in padella con i pomodorini',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'pesce', ruolo: 'proteina', gruppi: ['pesce'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'base', ruolo: 'base', gruppi: ['pane', 'cereale'], facoltativo: true },
    ],
    liberi: ['aglio', 'prezzemolo', 'sale', 'pepe'],
    passi: [
      'Fai saltare {verdura} con {grasso} e aglio, a fuoco vivo, finché non si spacca.',
      'Adagia {pesce} nel sugo, copri e cuoci otto minuti a fuoco basso.',
      'Non girarlo: si sfalda. Bagnalo col fondo con un cucchiaio.',
      'Servi con {base} per raccogliere il sugo.',
    ],
  },
  {
    id: 'tonno-insalata',
    titolo: 'Insalata di tonno e legumi',
    fasce: ['pranzo', 'cena'],
    minuti: 10,
    posti: [
      { chiave: 'tonno', ruolo: 'proteina', gruppi: ['pesce'] },
      { chiave: 'legumi', ruolo: 'base', gruppi: ['legume'], facoltativo: true },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['cipolla rossa', 'aceto', 'sale', 'origano'],
    passi: [
      'Sciacqua {legumi} e mettili in una ciotola.',
      'Aggiungi {verdura} a pezzi e {tonno} sgocciolato.',
      'Condisci con {grasso}, un filo d’aceto e origano.',
      'Lascia riposare dieci minuti prima di mangiarla.',
    ],
    nota: 'È il piatto del giorno in cui non hai voglia: si fa mentre pensi ad altro.',
  },

  // ─── Uova e latticini ─────────────────────────────────────────────────────
  {
    id: 'frittata-verdure',
    titolo: 'Frittata di verdure',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'uova', ruolo: 'proteina', gruppi: ['uova'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'formaggio', ruolo: 'latticino', gruppi: ['latticino'], facoltativo: true },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'], facoltativo: true },
    ],
    liberi: ['sale', 'pepe', 'prezzemolo'],
    passi: [
      'Cuoci {verdura} a pezzetti in padella con {grasso}, finché non perde l’acqua.',
      'Sbatti {uova} con {formaggio}, sale e pepe.',
      'Versa sulla verdura, abbassa il fuoco e copri.',
      'Quando la superficie è quasi rappresa, gira con l’aiuto di un piatto e finisci due minuti.',
      'Con {pane} accanto.',
    ],
  },
  {
    id: 'uova-pomodoro',
    titolo: 'Uova in purgatorio',
    fasce: ['pranzo', 'cena'],
    minuti: 20,
    posti: [
      { chiave: 'uova', ruolo: 'proteina', gruppi: ['uova'] },
      { chiave: 'pomodoro', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['aglio', 'peperoncino', 'basilico', 'sale'],
    passi: [
      'Fai il sugo con {pomodoro}, {grasso}, aglio e peperoncino: dieci minuti bastano.',
      'Apri {uova} dentro il sugo, distanti fra loro.',
      'Copri e cuoci sei minuti: il bianco deve rapprendersi, il rosso no.',
      'Porta in tavola nella padella, con {pane} per la scarpetta.',
    ],
  },
  {
    id: 'insalatona-formaggio',
    titolo: 'Insalatona con il formaggio',
    fasce: ['pranzo', 'cena'],
    minuti: 10,
    posti: [
      { chiave: 'formaggio', ruolo: 'proteina', gruppi: ['latticino'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'base', ruolo: 'base', gruppi: ['pane', 'cereale'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    liberi: ['aceto', 'sale', 'pepe'],
    passi: [
      'Taglia {verdura} e mettila in una ciotola larga.',
      'Aggiungi {formaggio} a pezzi e {semi}.',
      'Condisci con {grasso}, aceto, sale.',
      'Con {base} tostato accanto.',
    ],
  },

  // ─── Legumi ───────────────────────────────────────────────────────────────
  {
    id: 'legumi-in-umido',
    titolo: 'Legumi in umido',
    fasce: ['pranzo', 'cena'],
    minuti: 30,
    posti: [
      { chiave: 'legumi', ruolo: 'proteina', gruppi: ['legume'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'base', ruolo: 'base', gruppi: ['pane', 'cereale'], facoltativo: true },
    ],
    liberi: ['cipolla', 'alloro', 'sale', 'pepe'],
    passi: [
      'Soffriggi la cipolla in {grasso} con una foglia d’alloro.',
      'Unisci {verdura} a pezzi e falla insaporire cinque minuti.',
      'Aggiungi {legumi} e poca acqua, cuoci venti minuti a fuoco basso.',
      'Servi con {base}.',
    ],
  },
  {
    id: 'burger-legumi',
    titolo: 'Burger di legumi',
    fasce: ['pranzo', 'cena'],
    minuti: 30,
    posti: [
      { chiave: 'legumi', ruolo: 'proteina', gruppi: ['legume'] },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane', 'cereale'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['cipolla', 'cumino', 'sale', 'pepe', 'pangrattato'],
    passi: [
      'Schiaccia {legumi} con la forchetta: devono restare dei pezzi, non diventare crema.',
      'Impasta con cipolla tritata, cumino, sale e un po’ di pangrattato per legare.',
      'Forma i burger e cuocili in padella con {grasso}, cinque minuti per lato.',
      'Metti dentro {pane} con {verdura}.',
    ],
  },

  // ─── Contorni e piatti di verdura ─────────────────────────────────────────
  {
    id: 'verdure-forno',
    titolo: 'Verdure al forno',
    fasce: ['pranzo', 'cena'],
    minuti: 35,
    posti: [
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura', 'tubero'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['carne', 'pesce', 'latticino', 'uova', 'legume'], facoltativo: true },
      { chiave: 'base', ruolo: 'base', gruppi: ['pane', 'cereale'], facoltativo: true },
    ],
    liberi: ['sale', 'rosmarino', 'aglio'],
    passi: [
      'Taglia {verdura} a pezzi della stessa misura: è l’unico modo perché cuocia insieme.',
      'Condisci con {grasso}, sale, rosmarino e mettila in teglia in un solo strato.',
      'Trenta minuti a 200°, mescolando a metà.',
      'Accanto {proteina} e {base}.',
    ],
    nota: 'In un solo strato. Ammucchiate stufano invece di arrostire.',
  },
  {
    id: 'insalata-completa',
    titolo: 'Piatto freddo',
    fasce: ['pranzo', 'cena'],
    minuti: 12,
    posti: [
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['carne', 'pesce', 'uova', 'latticino', 'legume'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'base', ruolo: 'base', gruppi: ['cereale', 'pane', 'tubero'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['limone', 'sale', 'pepe', 'erbe'],
    passi: [
      'Se {base} va cotto, cuocilo e raffreddalo sotto l’acqua.',
      'Taglia {verdura} e {proteina} a pezzi della stessa misura.',
      'Mescola tutto con {grasso}, limone, sale.',
      'Meglio dopo mezz’ora in frigo.',
    ],
    nota: 'È la ricetta da portarsi dietro: si fa la sera prima e regge.',
  },
  {
    id: 'patate-e-proteina',
    titolo: 'Patate e secondo in teglia',
    fasce: ['pranzo', 'cena'],
    minuti: 45,
    posti: [
      { chiave: 'patate', ruolo: 'base', gruppi: ['tubero'] },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['carne', 'pesce'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['rosmarino', 'aglio', 'sale', 'pepe'],
    passi: [
      'Taglia {patate} a tocchetti e mettile in teglia con {grasso}, rosmarino e sale.',
      'Quindici minuti a 200° da sole: partono avvantaggiate.',
      'Aggiungi {proteina} e {verdura}, e vai avanti altri venticinque minuti.',
      'Mescola una volta sola, a metà.',
    ],
  },
  {
    id: 'zuppa-legumi',
    titolo: 'Zuppa di legumi',
    fasce: ['cena'],
    minuti: 40,
    posti: [
      { chiave: 'legumi', ruolo: 'proteina', gruppi: ['legume'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane', 'cereale'], facoltativo: true },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['sedano', 'carota', 'cipolla', 'alloro', 'sale', 'pepe'],
    passi: [
      'Fondo di sedano, carota e cipolla in {grasso}.',
      'Unisci {legumi}, {verdura} e acqua a coprire di due dita.',
      'Sobbolli mezz’ora con l’alloro. Sale alla fine.',
      'Frulla un mestolo e rimettilo dentro: si addensa senza farina.',
      'Servi con {pane} tostato.',
    ],
  },
  {
    id: 'cereale-verdure-proteina',
    titolo: 'Ciotola di cereale, verdura e proteina',
    fasce: ['pranzo', 'cena'],
    minuti: 25,
    posti: [
      { chiave: 'cereale', ruolo: 'base', gruppi: ['cereale'] },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['carne', 'pesce', 'legume', 'uova', 'latticino'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
      { chiave: 'semi', ruolo: 'semi', gruppi: ['frutta_secca'], facoltativo: true },
    ],
    liberi: ['limone', 'sale', 'pepe', 'erbe fresche'],
    passi: [
      'Cuoci {cereale} in acqua salata e scolalo.',
      'Cuoci {proteina} come preferisci: padella, forno o lessata.',
      'Salta {verdura} con {grasso}, o tienila cruda se è da insalata.',
      'Componi la ciotola a spicchi, non mescolata: cereale, verdura, proteina.',
      'Finisci con {semi}, limone e erbe.',
    ],
    nota: 'A spicchi e non mescolata: così ogni cucchiaio è diverso e il piatto non stufa.',
  },
  {
    id: 'pane-e-companatico',
    titolo: 'Pane e companatico',
    fasce: ['pranzo', 'cena'],
    minuti: 8,
    posti: [
      { chiave: 'pane', ruolo: 'base', gruppi: ['pane'] },
      { chiave: 'proteina', ruolo: 'proteina', gruppi: ['latticino', 'carne', 'pesce', 'uova'] },
      { chiave: 'verdura', ruolo: 'verdura', gruppi: ['verdura'] },
      { chiave: 'grasso', ruolo: 'grasso', gruppi: ['grasso'], facoltativo: true },
    ],
    liberi: ['sale', 'origano'],
    passi: [
      'Tosta {pane}.',
      'Sopra {proteina} e {verdura} a fette.',
      'Un filo di {grasso}, sale, origano.',
    ],
    nota: 'Serve nei giorni in cui l’alternativa vera è saltare il pasto.',
  },
]

/** Indice per id, che serve alla pagina della ricetta. */
export const PER_ID = new Map(LIBRO.map((r) => [r.id, r]))
